import React, { useState } from 'react';
import {
  Card,
  CardHeader,
  CardTitle,
  CardDescription,
  CardContent,
  CardFooter,
  Button,
  StatusBadge,
  ProgressBar,
  Modal,
} from '../components';

interface SelfTestStep {
  name: string;
  status: 'PENDING' | 'RUNNING' | 'PASSED' | 'FAILED';
  duration: string;
}

const INITIAL_SELF_TEST_STEPS: SelfTestStep[] = [
  { name: 'Khởi tạo CUDA Device Driver (RTX 4050)', status: 'PASSED', duration: '120ms' },
  { name: 'Kiểm tra tệp nhị phân ONNX Runtime GPU', status: 'PASSED', duration: '85ms' },
  { name: 'Kiểm tra Checksum Model Weights vi_voice_v1', status: 'PASSED', duration: '310ms' },
  { name: 'Xác thực cơ sở dữ liệu SQLite & Migration', status: 'PASSED', duration: '45ms' },
  { name: 'Kiểm tra bộ đệm âm thanh xuất bản 24kHz', status: 'PASSED', duration: '30ms' },
];

const SAMPLE_LOGS = `[2026-09-14 11:42:01.120] [INFO] [System] OmniVoice Desktop Client v0.3.0-alpha startup.
[2026-09-14 11:42:01.245] [INFO] [CUDA] NVIDIA GeForce RTX 4050 detected (Compute Capability 8.9).
[2026-09-14 11:42:01.310] [INFO] [CUDA] CUDA Driver 12.4 initialized. Total VRAM: 6144 MB.
[2026-09-14 11:42:01.405] [INFO] [Python] Python 3.12.3 runtime active (CPython 64-bit).
[2026-09-14 11:42:01.550] [INFO] [Storage] SQLite database opened: D:\\Tool Dich Cho Khach\\storage\\omnivoice.db
[2026-09-14 11:42:01.620] [INFO] [Audio] Audio backend initialized: 24,000 Hz, 1 channel (Mono).
[2026-09-14 11:42:01.890] [INFO] [Engine] Mock Engine Provider mounted. All subsystems ready.
[2026-09-14 11:45:10.040] [INFO] [TTS] Synthetic request completed: 18.4s audio produced in 1.42s.`;

export const DiagnosticsPage: React.FC = () => {
  // Mock Hardware metrics
  const vramUsedGb = 1.8;
  const vramTotalGb = 6.0;
  const vramPercent = Math.round((vramUsedGb / vramTotalGb) * 100);

  const ramUsedGb = 6.4;
  const ramTotalGb = 16.0;
  const ramPercent = Math.round((ramUsedGb / ramTotalGb) * 100);

  // Self Test state
  const [isRunningTest, setIsRunningTest] = useState(false);
  const [selfTestSteps, setSelfTestSteps] = useState<SelfTestStep[]>(INITIAL_SELF_TEST_STEPS);
  const [testComplete, setTestComplete] = useState(true);

  // Copy notification state
  const [copiedNotification, setCopiedNotification] = useState(false);

  // Logs modal
  const [isLogsOpen, setIsLogsOpen] = useState(false);

  // Run Self Test Simulation
  const handleRunSelfTest = () => {
    setIsRunningTest(true);
    setTestComplete(false);

    // Reset steps to pending
    setSelfTestSteps(
      INITIAL_SELF_TEST_STEPS.map((s) => ({ ...s, status: 'PENDING' }))
    );

    // Progressively execute steps
    let currentIdx = 0;
    const interval = window.setInterval(() => {
      setSelfTestSteps((prev) =>
        prev.map((step, idx) => {
          if (idx < currentIdx) return { ...step, status: 'PASSED' };
          if (idx === currentIdx) return { ...step, status: 'RUNNING' };
          return step;
        })
      );

      currentIdx++;

      if (currentIdx > INITIAL_SELF_TEST_STEPS.length) {
        clearInterval(interval);
        setSelfTestSteps(
          INITIAL_SELF_TEST_STEPS.map((s) => ({ ...s, status: 'PASSED' }))
        );
        setIsRunningTest(false);
        setTestComplete(true);
      }
    }, 400);
  };

  // Copy diagnostics JSON to clipboard
  const handleCopyDiagnostics = () => {
    const report = {
      timestamp: new Date().toISOString(),
      status: 'MOCK_PROVIDER_ACTIVE',
      connected: false,
      hardware: {
        gpu: 'NVIDIA GeForce RTX 4050',
        vram: `${vramUsedGb} GB / ${vramTotalGb} GB (${vramPercent}%)`,
        ram: `${ramUsedGb} GB / ${ramTotalGb} GB (${ramPercent}%)`,
        cuda: 'Available (v12.4)',
      },
      runtime: {
        python: 'Python 3.12.3',
        omnivoice: 'OmniVoice Ready (Mock Engine v1)',
        model: 'vi_voice_v1.onnx (Loaded)',
        audio: '24,000 Hz Mono (PCM)',
      },
      note: 'Values generated by Frontend Mock Architecture. Real Python backend not connected.',
    };

    navigator.clipboard.writeText(JSON.stringify(report, null, 2)).then(() => {
      setCopiedNotification(true);
      setTimeout(() => setCopiedNotification(false), 2500);
    });
  };

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '20px' }}>
      {/* Top Header */}
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: '16px' }}>
        <div>
          <h1 style={{ fontSize: '20px', fontWeight: 700, color: 'var(--neutral-900)' }}>
            Diagnostics (Chẩn đoán hệ thống)
          </h1>
          <p style={{ fontSize: '13px', color: 'var(--neutral-500)', marginTop: '2px' }}>
            Kiểm tra trạng thái phần cứng, GPU VRAM, mô hình và nhật ký thực thi cục bộ
          </p>
        </div>

        <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
          <StatusBadge status="warning" label="Mock Provider Active" size="sm" />
          <Button
            size="sm"
            variant="outline"
            onClick={handleCopyDiagnostics}
            iconLeft={
              <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <rect x="9" y="9" width="13" height="13" rx="2" ry="2"></rect>
                <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path>
              </svg>
            }
          >
            {copiedNotification ? 'Đã sao chép!' : 'Copy Diagnostics'}
          </Button>

          <Button
            size="sm"
            variant="outline"
            onClick={() => setIsLogsOpen(true)}
            iconLeft={
              <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path>
                <polyline points="14 2 14 8 20 8"></polyline>
              </svg>
            }
          >
            Open Logs
          </Button>

          <Button
            size="sm"
            variant="primary"
            isLoading={isRunningTest}
            onClick={handleRunSelfTest}
            iconLeft={
              <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <polyline points="22 12 18 12 15 21 9 3 6 12 2 12"></polyline>
              </svg>
            }
          >
            Run Self Test
          </Button>
        </div>
      </div>

      {/* Mock Notice Banner */}
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '10px 16px', background: 'var(--color-primary-50)', border: '1px solid var(--color-primary-200)', borderRadius: 'var(--radius-md)' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
          <StatusBadge status="info" label="NOTE" size="sm" showDot={false} />
          <span style={{ fontSize: '13px', color: 'var(--color-primary-900)' }}>
            Các thông số hiển thị dưới đây là <strong>giá trị mô phỏng (Mock Values)</strong> do chưa kết nối backend Python.
          </span>
        </div>
        <span style={{ fontSize: '12px', color: 'var(--color-primary-700)', fontFamily: 'var(--font-family-mono)' }}>
          CP0.3A-7 Verified
        </span>
      </div>

      {/* 6 Required Diagnostic Cards: GPU, CUDA, OmniVoice, Model, Python, Audio */}
      <div className="ds-diagnostics-grid">
        {/* 1. GPU */}
        <div className="ds-diagnostic-card">
          <div className="ds-diagnostic-header">
            <span className="ds-diagnostic-title">GPU Card</span>
            <StatusBadge status="success" label="Active" size="sm" />
          </div>
          <div className="ds-diagnostic-value">RTX 4050</div>
          <span style={{ fontSize: '12px', color: 'var(--neutral-500)' }}>
            NVIDIA GeForce Dedicated Graphics (6GB GDDR6)
          </span>
        </div>

        {/* 2. CUDA */}
        <div className="ds-diagnostic-card">
          <div className="ds-diagnostic-header">
            <span className="ds-diagnostic-title">CUDA Support</span>
            <StatusBadge status="success" label="Available" size="sm" />
          </div>
          <div className="ds-diagnostic-value">CUDA Available</div>
          <span style={{ fontSize: '12px', color: 'var(--neutral-500)' }}>
            Driver Version: 12.4 (Compute 8.9)
          </span>
        </div>

        {/* 3. OmniVoice */}
        <div className="ds-diagnostic-card">
          <div className="ds-diagnostic-header">
            <span className="ds-diagnostic-title">OmniVoice Core</span>
            <StatusBadge status="success" label="Ready" size="sm" />
          </div>
          <div className="ds-diagnostic-value">OmniVoice Ready</div>
          <span style={{ fontSize: '12px', color: 'var(--neutral-500)' }}>
            Local Inference Pipeline v1.0 (Zero API Fee)
          </span>
        </div>

        {/* 4. Model */}
        <div className="ds-diagnostic-card">
          <div className="ds-diagnostic-header">
            <span className="ds-diagnostic-title">Voice Model</span>
            <StatusBadge status="success" label="Loaded" size="sm" />
          </div>
          <div className="ds-diagnostic-value">Model Loaded</div>
          <span style={{ fontSize: '12px', color: 'var(--neutral-500)' }}>
            vi_voice_v1.onnx (FP16 Optimized)
          </span>
        </div>

        {/* 5. Python */}
        <div className="ds-diagnostic-card">
          <div className="ds-diagnostic-header">
            <span className="ds-diagnostic-title">Python Runtime</span>
            <StatusBadge status="success" label="Active" size="sm" />
          </div>
          <div className="ds-diagnostic-value">Python 3.12</div>
          <span style={{ fontSize: '12px', color: 'var(--neutral-500)' }}>
            Virtualenv .venv (64-bit Windows)
          </span>
        </div>

        {/* 6. Audio */}
        <div className="ds-diagnostic-card">
          <div className="ds-diagnostic-header">
            <span className="ds-diagnostic-title">Audio Pipeline</span>
            <StatusBadge status="success" label="Configured" size="sm" />
          </div>
          <div className="ds-diagnostic-value">24 kHz Mono</div>
          <span style={{ fontSize: '12px', color: 'var(--neutral-500)' }}>
            16-bit Linear PCM Audio Buffer
          </span>
        </div>
      </div>

      {/* Memory & VRAM Gauges */}
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(360px, 1fr))', gap: '20px' }}>
        {/* VRAM Usage Card */}
        <Card>
          <CardHeader>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
              <CardTitle>VRAM Mock Usage (RTX 4050)</CardTitle>
              <span style={{ fontSize: '13px', fontWeight: 600, color: 'var(--neutral-800)', fontFamily: 'var(--font-family-mono)' }}>
                {vramUsedGb} GB / {vramTotalGb} GB ({vramPercent}%)
              </span>
            </div>
            <CardDescription>Bộ nhớ đệm đồ họa đang được phân bổ cho mô hình suy luận</CardDescription>
          </CardHeader>
          <CardContent style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}>
            <ProgressBar value={vramPercent} size="md" status="default" />
            <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '12px', color: 'var(--neutral-500)' }}>
              <span>Đang dùng: {vramUsedGb} GB</span>
              <span>Còn trống: {(vramTotalGb - vramUsedGb).toFixed(1)} GB</span>
            </div>
          </CardContent>
        </Card>

        {/* System RAM Card */}
        <Card>
          <CardHeader>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
              <CardTitle>RAM Mock Usage (Hệ thống)</CardTitle>
              <span style={{ fontSize: '13px', fontWeight: 600, color: 'var(--neutral-800)', fontFamily: 'var(--font-family-mono)' }}>
                {ramUsedGb} GB / {ramTotalGb} GB ({ramPercent}%)
              </span>
            </div>
            <CardDescription>Bộ nhớ RAM máy tính cho tiến trình SQLite và xử lý văn bản</CardDescription>
          </CardHeader>
          <CardContent style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}>
            <ProgressBar value={ramPercent} size="md" status="default" />
            <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '12px', color: 'var(--neutral-500)' }}>
              <span>Đang dùng: {ramUsedGb} GB</span>
              <span>Còn trống: {(ramTotalGb - ramUsedGb).toFixed(1)} GB</span>
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Self Test Checklist Card */}
      <Card>
        <CardHeader>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
            <div>
              <CardTitle>Kết quả kiểm tra tự động (Self Test Checklist)</CardTitle>
              <CardDescription>Kiểm tra tính toàn vẹn của các thành phần cốt lõi</CardDescription>
            </div>
            {testComplete && (
              <StatusBadge status="success" label="All Checks Passed" size="sm" />
            )}
          </div>
        </CardHeader>

        <CardContent style={{ display: 'flex', flexDirection: 'column', gap: '8px' }}>
          {selfTestSteps.map((step, idx) => (
            <div
              key={idx}
              style={{
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'space-between',
                padding: '10px 14px',
                background: 'var(--surface-subtle)',
                borderRadius: 'var(--radius-md)',
                border: '1px solid var(--border-subtle)',
              }}
            >
              <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
                <StatusBadge
                  status={step.status === 'PASSED' ? 'success' : step.status === 'RUNNING' ? 'info' : 'neutral'}
                  label={step.status}
                  size="sm"
                />
                <span style={{ fontSize: '13px', color: 'var(--neutral-800)', fontWeight: 500 }}>
                  {step.name}
                </span>
              </div>
              <span style={{ fontSize: '12px', color: 'var(--neutral-500)', fontFamily: 'var(--font-family-mono)' }}>
                {step.status === 'PASSED' ? step.duration : '...'}
              </span>
            </div>
          ))}
        </CardContent>

        <CardFooter style={{ justifyContent: 'space-between' }}>
          <span style={{ fontSize: '12px', color: 'var(--neutral-500)' }}>
            Lần kiểm tra gần nhất: Vừa xong
          </span>
          <Button
            size="sm"
            variant="outline"
            isLoading={isRunningTest}
            onClick={handleRunSelfTest}
          >
            Chạy lại kiểm tra
          </Button>
        </CardFooter>
      </Card>

      {/* Logs Viewer Modal */}
      <Modal
        isOpen={isLogsOpen}
        onClose={() => setIsLogsOpen(false)}
        title="Nhật ký hệ thống (System Logs)"
        size="lg"
        footer={
          <div style={{ display: 'flex', justifyContent: 'space-between', width: '100%', alignItems: 'center' }}>
            <span style={{ fontSize: '12px', color: 'var(--neutral-500)' }}>
              Đường dẫn tệp: <code>D:\Tool Dich Cho Khach\logs\app.log</code>
            </span>
            <Button variant="outline" size="md" onClick={() => setIsLogsOpen(false)}>
              Đóng
            </Button>
          </div>
        }
      >
        <div style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
          <div className="ds-log-box">
            {SAMPLE_LOGS}
          </div>
        </div>
      </Modal>
    </div>
  );
};
