"""Small application error vocabulary; messages are controlled, not caller supplied."""
from enum import Enum


class ErrorCode(str, Enum):
    PROFILE_IN_USE = "PROFILE_IN_USE"
    JOB_NOT_FOUND = "JOB_NOT_FOUND"
    INTERNAL_ERROR = "INTERNAL_ERROR"
    INVALID_REQUEST = "INVALID_REQUEST"
    SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE"
    NOT_FOUND = "NOT_FOUND"
    METHOD_NOT_ALLOWED = "METHOD_NOT_ALLOWED"
    PROVIDER_NOT_FOUND = "PROVIDER_NOT_FOUND"
    PROVIDER_UNAVAILABLE = "PROVIDER_UNAVAILABLE"
    PROVIDER_LOAD_FAILED = "PROVIDER_LOAD_FAILED"
    PROVIDER_NOT_READY = "PROVIDER_NOT_READY"
    INVALID_TEXT = "INVALID_TEXT"
    TEXT_TOO_LONG = "TEXT_TOO_LONG"
    LANGUAGE_NOT_SUPPORTED = "LANGUAGE_NOT_SUPPORTED"
    VOICE_NOT_FOUND = "VOICE_NOT_FOUND"
    INVALID_SPEED = "INVALID_SPEED"
    INVALID_FORMAT = "INVALID_FORMAT"
    GENERATION_FAILED = "GENERATION_FAILED"
    AUDIO_EXPORT_FAILED = "AUDIO_EXPORT_FAILED"
    ARTIFACT_NOT_FOUND = "ARTIFACT_NOT_FOUND"
    INVALID_REFERENCE_AUDIO = "INVALID_REFERENCE_AUDIO"
    REFERENCE_AUDIO_TOO_LARGE = "REFERENCE_AUDIO_TOO_LARGE"
    INVALID_REFERENCE_TRANSCRIPT = "INVALID_REFERENCE_TRANSCRIPT"
    VOICE_PROFILE_CREATION_FAILED = "VOICE_PROFILE_CREATION_FAILED"
    VOICE_PROFILE_NOT_FOUND = "VOICE_PROFILE_NOT_FOUND"
    VOICE_PROFILE_NOT_READY = "VOICE_PROFILE_NOT_READY"
    CLONE_GENERATION_FAILED = "CLONE_GENERATION_FAILED"


class ApplicationError(Exception):
    def __init__(self, code: ErrorCode):
        self.code = code
        super().__init__(code.value)
